version: '3.8'

services:
  app:
    container_name: portal-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - DEBUG=1
    env_file:
      - .env