interface Country {
  [key: string]: string[];
}

const europeCountry: Country = {
  en: [
    'Albania',
    'Andorra',
    'Armenia',
    'Austria',
    'Azerbaijan',
    'Belarus',
    'Belgium',
    'Bosnia',
    'Bulgaria',
    'Croatia',
    'Cyprus',
    'Czechia',
    'Denmark',
    'Estonia',
    'Finland',
    'France',
    'Georgia',
    'Germany',
    'Greece',
    'Herzegovina',
    'Hungary',
    'Iceland',
    'Ireland',
    'Italy',
    'Kazakhstan',
    'Kosovo',
    'Latvia',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Malta',
    'Moldova',
    'Monaco',
    'Montenegro',
    'Netherlands',
    'North Macedonia',
    'Norway',
    'Poland',
    'Portugal',
    'Romania',
    'Russia',
    'San Marino',
    'Serbia',
    'Slovakia',
    'Slovenia',
    'Spain',
    'Sweden',
    'Switzerland',
    'Turkey',
    'Ukraine',
    'United Kingdom',
    'Vatican',
  ],
  it: [
    'Albania',
    'Andorra',
    'Armenia',
    'Austria',
    'Azerbaijan',
    'Belgio',
    'Bielorussia',
    'Bosnia',
    'Bulgaria',
    'Cipro',
    'Croazia',
    'Danimarca',
    'Estonia',
    'Finlandia',
    'Francia',
    'Erzegovina',
    'Georgia',
    'Germania',
    'Grecia',
    'Irlanda',
    'Islanda',
    'Italia',
    'Kazakistan',
    'Kosovo',
    'Lettonia',
    'Liechtenstein',
    'Lituania',
    'Lussemburgo',
    'Macedonia del Nord',
    'Malta',
    'Moldova',
    'Monaco',
    'Montenegro',
    'Norvegia',
    'Olanda',
    'Polonia',
    'Portogallo',
    'Repubblica Ceca',
    'Romania',
    'Russia',
    'San Marino',
    'Serbia',
    'Slovacchia',
    'Slovenia',
    'Spagna',
    'Spain',
    'Svizzero',
    'Tacchino',
    'Ucraino',
    'Ungheria',
    'Regno Unito',
    'Vaticano',
  ],
  fr: [
    'Albanie',
    'Andorre',
    'Arménie',
    'Autriche',
    'Azerbaïdjan',
    'Biélorussie',
    'Belgique',
    'Bosnie',
    'Bulgarie',
    'Croatie',
    'Chypre',
    'Tchéquie',
    'Danemark',
    'Estonie',
    'Finlande',
    'France',
    'Géorgie',
    'Allemagne',
    'Grèce',
    'Herzégovine',
    'Hongrie',
    'Islande',
    'Irlande',
    'Italie',
    'Kazakhstan',
    'Kosovo',
    'Lettonie',
    'Liechtenstein',
    'Lituanie',
    'Luxembourg',
    'Malte',
    'Moldavie',
    'Monaco',
    'Monténégro',
    'Pays-Bas',
    'Macédoine du Nord',
    'Norvège',
    'Pologne',
    'le Portugal',
    'Roumanie',
    'Russie',
    'Saint Marin',
    'Serbie',
    'Slovaquie',
    'Slovénie',
    'Espagne',
    'Suède',
    'Suisse',
    'dinde',
    'Ukraine',
    'Royaume-Uni',
    'Vatican',
  ],
  es: [
    'Albania',
    'Andorra',
    'Armenia',
    'Austria',
    'Azerbaiyán',
    'Bielorrusia',
    'Bélgica',
    'Bosnia',
    'Bulgaria',
    'Croacia',
    'Chipre',
    'Chequia',
    'Dinamarca',
    'Estonia',
    'Finlandia',
    'Francia',
    'Georgia',
    'Alemania',
    'Grecia',
    'Herzegovina',
    'Hungría',
    'Islandia',
    'Irlanda',
    'Italia',
    'Kazajstán',
    'Kosovo',
    'Letonia',
    'Liechtenstein',
    'Lituania',
    'Luxemburgo',
    'Malta',
    'Moldavia',
    'Mónaco',
    'Montenegro',
    'Países Bajos',
    'Macedonia del Norte',
    'Noruega',
    'Polonia',
    'Portugal',
    'Rumania',
    'Rusia',
    'San Marino',
    'Serbia',
    'Eslovaquia',
    'Eslovenia',
    'España',
    'Suecia',
    'suizo',
    'pavo',
    'Ucrania',
    'Reino Unido',
    'Vaticano',
  ],
};

export default europeCountry;
